// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jxsxbtiasjujksyzrxdn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp4c3hidGlhc2p1amtzeXpyeGRuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAzNTcxMzYsImV4cCI6MjA2NTkzMzEzNn0.7tiXBddCW_1mIcLz03OFQr3apNRxGG0nnc-r1YQX6FE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);